dist: trusty
sudo: false
language: elm
addons:
  chrome: stable

services:
  - docker

cache:
  directories: # so subsequent builds run faster
    - elm-stuff
    - $HOME/.elm
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - elm-format --validate .
  - npm run test:ci
  - docker build -t "nakadi/nakadi-ui:${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}" .
  - docker tag "nakadi/nakadi-ui:${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}" nakadi/nakadi-ui:latest

deploy:
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push nakadi/nakadi-ui
  on:
    branch: master
