language: elm

cache:
  directories: # so subsequent builds run faster
    - elm-stuff
    - $HOME/.elm
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

script:
  elm-format --validate . && elm-test
