dist: bionic
sudo: false
language: node_js
node_js:
  - "11"

addons:
  apt:
    packages:
      - chromium-browser

services:
  - docker

cache:
  directories: # so subsequent builds run faster
    - elm-stuff
    - $HOME/.elm
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249
before_install:
  - chromium-browser --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run validate
  - npm run test:ci
  - npm run codecov
  - docker build -t "nakadi/nakadi-ui:${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}" .
  - docker tag "nakadi/nakadi-ui:${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}" nakadi/nakadi-ui:latest
