language: node_js
node_js: node

env:
  - ELM_VERSION=0.19.0

cache:
  directories: # so subsequent builds run faster
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION
  # Faster compile on Travis.
  - |
      if [ ! -d sysconfcpus/bin ];
      then
        git clone https://github.com/obmarg/libsysconfcpus.git;
        cd libsysconfcpus;
        ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
        make && make install;
        cd ..;
      fi
  - npm install
  - elm package install -y

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 npm run test:client
