X-Zalando-Team: aruha
X-Zalando-Type: code

approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando

specification:
  title:
    minimum-length:
      enabled: true
      length: 8
  body:
    minimum-length:
      enabled: true
      length: 8
