version: "2017-09-20"
pipeline:
  - id: build
    overlay: ci/nodejs
    cache:
      paths:
        - ~/.npm
        - ~/.elm
        - ./elm-stuff
        - ./node_modules
    type: script
    commands:
      - desc: Install deps
        cmd: |
          apt-get update
          apt-get -yq --no-install-suggests --no-install-recommends install chromium-browser
          # Fix for problem with permissions elm-format
          # https://github.com/avh4/elm-format/issues/554
          npm ci --unsafe-perm=true

      - desc: Validate formatting
        cmd: |
          npm run validate

      - desc: Run tests
        cmd: |
          npm run test:ci

      - desc: Build docker image
        cmd: |
          IMAGE=registry-write.opensource.zalan.do/aruha/nakadi-ui:${CDP_BUILD_VERSION}
          docker build --pull=false -t $IMAGE .

      - desc: Push docker image if master
        cmd: |
          if [ -z "$CDP_PULL_REQUEST_NUMBER" ]; then
            docker push $IMAGE
          else
            echo "Skipping non-master builds."
          fi
